# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alien < Formula
  desc "Quick command-line aliases. Run a command, like it, type alien <name>."
  homepage "https://gitlab.com/nickdonnelly/alien"
  version "0.0.9"
  license "MIT"

  depends_on "fzf" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nickdonnelly/alien/releases/download/v0.0.9/alien_0.0.9_darwin_amd64.tar.gz"
      sha256 "89c3b04d2cdf59411f9c87a25cba075ac9d76eed5a69f1412293e7f01631cc82"

      define_method(:install) do
        bin.install "alien"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nickdonnelly/alien/releases/download/v0.0.9/alien_0.0.9_darwin_arm64.tar.gz"
      sha256 "0cfad7ac25de3b87c090af92d10ea495544c45c3d28866b4d6b73e8306c9f9d2"

      define_method(:install) do
        bin.install "alien"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nickdonnelly/alien/releases/download/v0.0.9/alien_0.0.9_linux_amd64.tar.gz"
      sha256 "182c36e46e2f29a4987870889ff8196167147761b08fd53ffd64b9b4a73c19e0"
      define_method(:install) do
        bin.install "alien"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nickdonnelly/alien/releases/download/v0.0.9/alien_0.0.9_linux_arm64.tar.gz"
      sha256 "64a5051e50e8f742c545ba7a2adc1112cbe023a9d43b2993da6d79507a7dcaa5"
      define_method(:install) do
        bin.install "alien"
      end
    end
  end
end
